services:
  - type: web
    name: student-attendance-system
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
